local number = 10
print(math.abs(number))
print(math.acos(number))
print(math.asin(number))
print(math.atan(number, 10))
print(math.ceil(number))
print(math.cos(number))
print(math.exp(number))
print(math.floor(number))
print(math.log(number))
print(math.max(number, 10))
print(math.min(number, 10))
print(math.rad(number))
print(math.random())
print(math.sin(number))
print(math.sqrt(number))
print(math.tan(number))
print(math.huge)
print(math.random(number))
print(math.maxinteger)