[package]
description = "The disassembler for Lua. Accepts bytes and returns assembly tokens"
name = "lulu_lib_web"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/ikremniou/Lulu"
license = "MIT"
authors = ["Ilya Kremniou <i@kremniou.ru>"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
lulu_lib = { path = "../lib" }
wasm-bindgen = "0.2.84"
